AWSTemplateFormatVersion: '2010-09-09'
Description: 'Book scraping Lambda functions'

Resources:
  ScrapeOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: scrape-output

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub '${ScrapeOutputBucket}/*'

  ScrapeBooksFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: scrape-books
      Runtime: python3.9
      Handler: scrape_books.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Upload deployment package'}
      Timeout: 300

  ScrapeBooksWithCategoriesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: scrape-books-with-categories
      Runtime: python3.9
      Handler: scrape_books_with_categories.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Upload deployment package'}
      Timeout: 300

Outputs:
  BucketName:
    Value: !Ref ScrapeOutputBucket
  ScrapeBooksArn:
    Value: !GetAtt ScrapeBooksFunction.Arn
  ScrapeBooksWithCategoriesArn:
    Value: !GetAtt ScrapeBooksWithCategoriesFunction.Arn
